services:
  recorder:
    build: .
    container_name: gaze_capture
    network_mode: host

    # --- Eye Tracker Access ---
    device_cgroup_rules:
      - 'c 189:* rmw'

    # --- Volumes ---
    volumes:
      # For communicating with the X server
      - /tmp/.X11-unix:/tmp/.X11-unix

      # USB
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
      
      # --- Data Persistence ---
      - /home/ternuser/zhaw/data/:/app/data/
      # - /home/regd/AWARE/apr25/:/app/data/

    # --- GUI Forwarding Configuration ---
    environment:
    # Pass host UID/GID to the entrypoint
      - PUID=1000
      - PGID=1000

      - DISPLAY=${DISPLAY}
      - GAZE__DATA_DIR=/app/data
      - GAZE__NATS_HOST=nats://localhost:4222
      - GAZE__LOGGING__LEVEL=INFO
      - GAZE__USE_DUMMY_MODE=false

      # Screen dimensions
      # - GAZE__DISPLAY_AREA__HEIGHT_PX=1600 
      # - GAZE__DISPLAY_AREA__WIDTH_PX=2400
      # - GAZE__DISPLAY_AREA__WIDTH_MM=310.0
      # - GAZE__DISPLAY_AREA__HEIGHT_MM=210.0
      - GAZE__DISPLAY_AREA__HEIGHT_PX=2160 
      - GAZE__DISPLAY_AREA__WIDTH_PX=3840 
      - GAZE__DISPLAY_AREA__WIDTH_MM=937.20
      - GAZE__DISPLAY_AREA__HEIGHT_MM=527.17   
      - GAZE__DISPLAY_AREA__VERTICAL_OFFSET_MM=0
      - GAZE__DISPLAY_AREA__HORIZONTAL_OFFSET_MM=0
      - GAZE__DISPLAY_AREA__DEPTH_OFFSET_MM=0